language: erlang
otp_release:
  - 17.0
  - R16B03-1
  - R16B03
  - R16B02
  - R16B01
  - R15B03
  - R15B02
  - R15B01
  - R14B04
  - R14B03
  - R14B02

# Required by Yaws.
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libpam0g-dev

notifications:
  email:
    recipients:
      - jean-sebastien.pedron@dumbbell.fr
    on_success: change
    on_failure: always
